# OpenSLO Example: Payment API Availability
# This SLO tracks the availability of the payment API service

apiVersion: openslo/v1
kind: SLO
metadata:
  name: payment-api-availability
  displayName: Payment API Availability
  labels:
    team: platform
    tier: "1"
    service: payment-api
    owner: john@company.com

spec:
  service: payment-api
  description: Payment API must be available 99.95% of the time over 30 days
  
  objectives:
    - target: 0.9995  # 99.95% availability
      indicator:
        spec:
          # Prometheus query for availability SLI
          # Measures: (successful requests) / (total requests)
          query: |
            sum(rate(http_requests_total{service="payment-api",status=~"2.."}[5m]))
            /
            sum(rate(http_requests_total{service="payment-api"}[5m]))
  
  timeWindow:
    - duration: 30d
      type: rolling
