# Full NthLayer CI/CD Pipeline
#
# This workflow provides comprehensive reliability validation:
# - PR: Plan check with comment
# - Merge to main: Deployment gate check
# - Nightly: Drift detection audit
#
# Prerequisites:
#   - PROMETHEUS_URL secret configured
#   - Service YAML files in your repository

name: NthLayer Full Pipeline

on:
  pull_request:
    branches: [main]
    paths:
      - 'services/**/*.yaml'
  push:
    branches: [main]
    paths:
      - 'services/**/*.yaml'
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

env:
  PROMETHEUS_URL: ${{ secrets.PROMETHEUS_URL }}

jobs:
  # PR Check: Validate configuration and preview changes
  pr-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Find changed services
        id: changed
        run: |
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- 'services/**/*.yaml' | tr '\n' ' ')
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: Run NthLayer Plan
        if: steps.changed.outputs.files != ''
        uses: rsionnach/nthlayer@v1
        with:
          command: plan
          service: ${{ steps.changed.outputs.files }}
          fail-on: error
          comment: 'true'
          upload-sarif: 'true'

  # Deployment Gate: Check error budget before merge
  deployment-gate:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Run Deployment Gate Check
        uses: rsionnach/nthlayer@v1
        with:
          command: check-deploy
          service: services/
          prometheus-url: ${{ env.PROMETHEUS_URL }}
          environment: prod
          fail-on: error

  # Nightly Audit: Check drift across all services
  nightly-audit:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install NthLayer
        run: pip install nthlayer

      - name: Run Drift Detection
        id: drift
        run: |
          # Check drift for all services
          mkdir -p reports
          for service in services/*.yaml; do
            NAME=$(basename "$service" .yaml)
            nthlayer drift "$service" \
              --prometheus-url "${{ env.PROMETHEUS_URL }}" \
              --format markdown > "reports/${NAME}-drift.md" 2>&1 || true
          done

          # Combine reports
          cat reports/*-drift.md > reports/combined-drift.md

      - name: Create Issue if Drift Detected
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('reports/combined-drift.md', 'utf8');

            // Check if there are any warnings or errors
            if (report.includes('Warning') || report.includes('Fail')) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `[NthLayer] Drift detected - ${new Date().toISOString().split('T')[0]}`,
                body: `## Nightly Drift Detection Report\n\n${report}`,
                labels: ['reliability', 'drift-detection']
              });
            }
