# Development Environment Overrides
# Applied when using --env dev

environment: dev

# Override service-level fields
service:
  tier: low  # Relaxed tier in dev

# Override resources
resources:
  # Relaxed SLO targets for dev
  - kind: SLO
    name: availability
    spec:
      objective: 99.0  # Lower than prod (99.9%)
  
  - kind: SLO
    name: latency-p95
    spec:
      objective: 90.0  # Relaxed
      threshold_ms: 2000  # Higher tolerance
  
  # PagerDuty - low urgency in dev (don't page)
  - kind: PagerDuty
    name: primary
    spec:
      urgency: low  # Create tickets, don't page
